name: Build and Push Backend Docker Image

on:
  push:
    branches:
      - main
      - develop
    paths:
      - 'packages/backend/**'
      - '.github/workflows/build-and-push-backend.yml'
  release:
    types: [published]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: samuelprak/payflow-backend

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha,format=short
            type=sha,format=long
            latest

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./packages/backend/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    name: Deploy on Preprod
    needs: [build-and-push]
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:

    - name: Checkout main
      uses: actions/checkout@v2

    - name: Preprod - Set Kubernetes context
      uses: azure/k8s-set-context@v2
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.KUBECONFIG_PREPROD }}

    - name: Deploy
      run: |
        kubectl apply -f ./k8s/secrets/sealed-payflow-preprod-secrets.yaml
        helm upgrade --install payflow ./k8s/helm/payflow \
          --namespace payflow-preprod \
          --values k8s/helm/payflow/values.yaml \
          --values k8s/helm/payflow/values-preprod.yaml \
          --set image.tag=sha-${{ github.sha }}
        kubectl rollout restart deployment payflow -n payflow-preprod
        kubectl rollout status deployment payflow -n payflow-preprod
